development:
  adapter: postgresql
  encoding: unicode
  database: sample_app_development
  pool: 5
  username: mulbree
  password: spikS^lEz~93

test:
  adapter: postgresql
  encoding: unicode
  database: sample_app_test
  pool: 5
  username: mulbree
  password: spikS^lEz~93

production:
  adapter: postgresql
  encoding: unicode
  database: sample_app_production
  pool: 5
  username: mulbree
  password: spikS^lEz~93
